# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _gappa_swig
else:
    import _gappa_swig

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _gappa_swig.delete_SwigPyIterator

    def value(self):
        return _gappa_swig.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _gappa_swig.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _gappa_swig.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _gappa_swig.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _gappa_swig.SwigPyIterator_equal(self, x)

    def copy(self):
        return _gappa_swig.SwigPyIterator_copy(self)

    def next(self):
        return _gappa_swig.SwigPyIterator_next(self)

    def __next__(self):
        return _gappa_swig.SwigPyIterator___next__(self)

    def previous(self):
        return _gappa_swig.SwigPyIterator_previous(self)

    def advance(self, n):
        return _gappa_swig.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _gappa_swig.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _gappa_swig.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _gappa_swig.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _gappa_swig.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _gappa_swig.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _gappa_swig.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _gappa_swig:
_gappa_swig.SwigPyIterator_swigregister(SwigPyIterator)
class ios_base(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    erase_event = _gappa_swig.ios_base_erase_event
    imbue_event = _gappa_swig.ios_base_imbue_event
    copyfmt_event = _gappa_swig.ios_base_copyfmt_event

    def register_callback(self, __fn, __index):
        return _gappa_swig.ios_base_register_callback(self, __fn, __index)

    def flags(self, *args):
        return _gappa_swig.ios_base_flags(self, *args)

    def setf(self, *args):
        return _gappa_swig.ios_base_setf(self, *args)

    def unsetf(self, __mask):
        return _gappa_swig.ios_base_unsetf(self, __mask)

    def precision(self, *args):
        return _gappa_swig.ios_base_precision(self, *args)

    def width(self, *args):
        return _gappa_swig.ios_base_width(self, *args)

    @staticmethod
    def sync_with_stdio(__sync=True):
        return _gappa_swig.ios_base_sync_with_stdio(__sync)

    def imbue(self, __loc):
        return _gappa_swig.ios_base_imbue(self, __loc)

    def getloc(self):
        return _gappa_swig.ios_base_getloc(self)

    @staticmethod
    def xalloc():
        return _gappa_swig.ios_base_xalloc()

    def iword(self, __ix):
        return _gappa_swig.ios_base_iword(self, __ix)

    def pword(self, __ix):
        return _gappa_swig.ios_base_pword(self, __ix)
    __swig_destroy__ = _gappa_swig.delete_ios_base

# Register ios_base in _gappa_swig:
_gappa_swig.ios_base_swigregister(ios_base)
cvar = _gappa_swig.cvar
ios_base.boolalpha = _gappa_swig.cvar.ios_base_boolalpha
ios_base.dec = _gappa_swig.cvar.ios_base_dec
ios_base.fixed = _gappa_swig.cvar.ios_base_fixed
ios_base.hex = _gappa_swig.cvar.ios_base_hex
ios_base.internal = _gappa_swig.cvar.ios_base_internal
ios_base.left = _gappa_swig.cvar.ios_base_left
ios_base.oct = _gappa_swig.cvar.ios_base_oct
ios_base.right = _gappa_swig.cvar.ios_base_right
ios_base.scientific = _gappa_swig.cvar.ios_base_scientific
ios_base.showbase = _gappa_swig.cvar.ios_base_showbase
ios_base.showpoint = _gappa_swig.cvar.ios_base_showpoint
ios_base.showpos = _gappa_swig.cvar.ios_base_showpos
ios_base.skipws = _gappa_swig.cvar.ios_base_skipws
ios_base.unitbuf = _gappa_swig.cvar.ios_base_unitbuf
ios_base.uppercase = _gappa_swig.cvar.ios_base_uppercase
ios_base.adjustfield = _gappa_swig.cvar.ios_base_adjustfield
ios_base.basefield = _gappa_swig.cvar.ios_base_basefield
ios_base.floatfield = _gappa_swig.cvar.ios_base_floatfield
ios_base.badbit = _gappa_swig.cvar.ios_base_badbit
ios_base.eofbit = _gappa_swig.cvar.ios_base_eofbit
ios_base.failbit = _gappa_swig.cvar.ios_base_failbit
ios_base.goodbit = _gappa_swig.cvar.ios_base_goodbit
ios_base.app = _gappa_swig.cvar.ios_base_app
ios_base.ate = _gappa_swig.cvar.ios_base_ate
ios_base.binary = _gappa_swig.cvar.ios_base_binary
ios_base.ios_base_in = _gappa_swig.cvar.ios_base_ios_base_in
ios_base.out = _gappa_swig.cvar.ios_base_out
ios_base.trunc = _gappa_swig.cvar.ios_base_trunc
ios_base.beg = _gappa_swig.cvar.ios_base_beg
ios_base.cur = _gappa_swig.cvar.ios_base_cur
ios_base.end = _gappa_swig.cvar.ios_base_end

class ios(ios_base):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def rdstate(self):
        return _gappa_swig.ios_rdstate(self)

    def clear(self, *args):
        return _gappa_swig.ios_clear(self, *args)

    def setstate(self, __state):
        return _gappa_swig.ios_setstate(self, __state)

    def good(self):
        return _gappa_swig.ios_good(self)

    def eof(self):
        return _gappa_swig.ios_eof(self)

    def fail(self):
        return _gappa_swig.ios_fail(self)

    def bad(self):
        return _gappa_swig.ios_bad(self)

    def exceptions(self, *args):
        return _gappa_swig.ios_exceptions(self, *args)

    def __init__(self, __sb):
        _gappa_swig.ios_swiginit(self, _gappa_swig.new_ios(__sb))
    __swig_destroy__ = _gappa_swig.delete_ios

    def tie(self, *args):
        return _gappa_swig.ios_tie(self, *args)

    def rdbuf(self, *args):
        return _gappa_swig.ios_rdbuf(self, *args)

    def copyfmt(self, __rhs):
        return _gappa_swig.ios_copyfmt(self, __rhs)

    def fill(self, *args):
        return _gappa_swig.ios_fill(self, *args)

    def imbue(self, __loc):
        return _gappa_swig.ios_imbue(self, __loc)

    def narrow(self, __c, __dfault):
        return _gappa_swig.ios_narrow(self, __c, __dfault)

    def widen(self, __c):
        return _gappa_swig.ios_widen(self, __c)

# Register ios in _gappa_swig:
_gappa_swig.ios_swigregister(ios)
class ostream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _gappa_swig.ostream_swiginit(self, _gappa_swig.new_ostream(__sb))
    __swig_destroy__ = _gappa_swig.delete_ostream

    def __lshift__(self, *args):
        return _gappa_swig.ostream___lshift__(self, *args)

    def put(self, __c):
        return _gappa_swig.ostream_put(self, __c)

    def write(self, __s, __n):
        return _gappa_swig.ostream_write(self, __s, __n)

    def flush(self):
        return _gappa_swig.ostream_flush(self)

    def tellp(self):
        return _gappa_swig.ostream_tellp(self)

    def seekp(self, *args):
        return _gappa_swig.ostream_seekp(self, *args)

# Register ostream in _gappa_swig:
_gappa_swig.ostream_swigregister(ostream)
class istream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _gappa_swig.istream_swiginit(self, _gappa_swig.new_istream(__sb))
    __swig_destroy__ = _gappa_swig.delete_istream

    def __rshift__(self, *args):
        return _gappa_swig.istream___rshift__(self, *args)

    def gcount(self):
        return _gappa_swig.istream_gcount(self)

    def get(self, *args):
        return _gappa_swig.istream_get(self, *args)

    def getline(self, *args):
        return _gappa_swig.istream_getline(self, *args)

    def ignore(self, *args):
        return _gappa_swig.istream_ignore(self, *args)

    def peek(self):
        return _gappa_swig.istream_peek(self)

    def read(self, __s, __n):
        return _gappa_swig.istream_read(self, __s, __n)

    def readsome(self, __s, __n):
        return _gappa_swig.istream_readsome(self, __s, __n)

    def putback(self, __c):
        return _gappa_swig.istream_putback(self, __c)

    def unget(self):
        return _gappa_swig.istream_unget(self)

    def sync(self):
        return _gappa_swig.istream_sync(self)

    def tellg(self):
        return _gappa_swig.istream_tellg(self)

    def seekg(self, *args):
        return _gappa_swig.istream_seekg(self, *args)

# Register istream in _gappa_swig:
_gappa_swig.istream_swigregister(istream)
class iostream(istream, ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _gappa_swig.iostream_swiginit(self, _gappa_swig.new_iostream(__sb))
    __swig_destroy__ = _gappa_swig.delete_iostream

# Register iostream in _gappa_swig:
_gappa_swig.iostream_swigregister(iostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

endl_cb_ptr = _gappa_swig.endl_cb_ptr
endl = _gappa_swig.endl
ends_cb_ptr = _gappa_swig.ends_cb_ptr
ends = _gappa_swig.ends
flush_cb_ptr = _gappa_swig.flush_cb_ptr
flush = _gappa_swig.flush
class OneIVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _gappa_swig.OneIVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _gappa_swig.OneIVector___nonzero__(self)

    def __bool__(self):
        return _gappa_swig.OneIVector___bool__(self)

    def __len__(self):
        return _gappa_swig.OneIVector___len__(self)

    def __getslice__(self, i, j):
        return _gappa_swig.OneIVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _gappa_swig.OneIVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _gappa_swig.OneIVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _gappa_swig.OneIVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _gappa_swig.OneIVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _gappa_swig.OneIVector___setitem__(self, *args)

    def pop(self):
        return _gappa_swig.OneIVector_pop(self)

    def append(self, x):
        return _gappa_swig.OneIVector_append(self, x)

    def empty(self):
        return _gappa_swig.OneIVector_empty(self)

    def size(self):
        return _gappa_swig.OneIVector_size(self)

    def swap(self, v):
        return _gappa_swig.OneIVector_swap(self, v)

    def begin(self):
        return _gappa_swig.OneIVector_begin(self)

    def end(self):
        return _gappa_swig.OneIVector_end(self)

    def rbegin(self):
        return _gappa_swig.OneIVector_rbegin(self)

    def rend(self):
        return _gappa_swig.OneIVector_rend(self)

    def clear(self):
        return _gappa_swig.OneIVector_clear(self)

    def get_allocator(self):
        return _gappa_swig.OneIVector_get_allocator(self)

    def pop_back(self):
        return _gappa_swig.OneIVector_pop_back(self)

    def erase(self, *args):
        return _gappa_swig.OneIVector_erase(self, *args)

    def __init__(self, *args):
        _gappa_swig.OneIVector_swiginit(self, _gappa_swig.new_OneIVector(*args))

    def push_back(self, x):
        return _gappa_swig.OneIVector_push_back(self, x)

    def front(self):
        return _gappa_swig.OneIVector_front(self)

    def back(self):
        return _gappa_swig.OneIVector_back(self)

    def assign(self, n, x):
        return _gappa_swig.OneIVector_assign(self, n, x)

    def resize(self, *args):
        return _gappa_swig.OneIVector_resize(self, *args)

    def insert(self, *args):
        return _gappa_swig.OneIVector_insert(self, *args)

    def reserve(self, n):
        return _gappa_swig.OneIVector_reserve(self, n)

    def capacity(self):
        return _gappa_swig.OneIVector_capacity(self)
    __swig_destroy__ = _gappa_swig.delete_OneIVector

# Register OneIVector in _gappa_swig:
_gappa_swig.OneIVector_swigregister(OneIVector)
class OneDVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _gappa_swig.OneDVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _gappa_swig.OneDVector___nonzero__(self)

    def __bool__(self):
        return _gappa_swig.OneDVector___bool__(self)

    def __len__(self):
        return _gappa_swig.OneDVector___len__(self)

    def __getslice__(self, i, j):
        return _gappa_swig.OneDVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _gappa_swig.OneDVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _gappa_swig.OneDVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _gappa_swig.OneDVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _gappa_swig.OneDVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _gappa_swig.OneDVector___setitem__(self, *args)

    def pop(self):
        return _gappa_swig.OneDVector_pop(self)

    def append(self, x):
        return _gappa_swig.OneDVector_append(self, x)

    def empty(self):
        return _gappa_swig.OneDVector_empty(self)

    def size(self):
        return _gappa_swig.OneDVector_size(self)

    def swap(self, v):
        return _gappa_swig.OneDVector_swap(self, v)

    def begin(self):
        return _gappa_swig.OneDVector_begin(self)

    def end(self):
        return _gappa_swig.OneDVector_end(self)

    def rbegin(self):
        return _gappa_swig.OneDVector_rbegin(self)

    def rend(self):
        return _gappa_swig.OneDVector_rend(self)

    def clear(self):
        return _gappa_swig.OneDVector_clear(self)

    def get_allocator(self):
        return _gappa_swig.OneDVector_get_allocator(self)

    def pop_back(self):
        return _gappa_swig.OneDVector_pop_back(self)

    def erase(self, *args):
        return _gappa_swig.OneDVector_erase(self, *args)

    def __init__(self, *args):
        _gappa_swig.OneDVector_swiginit(self, _gappa_swig.new_OneDVector(*args))

    def push_back(self, x):
        return _gappa_swig.OneDVector_push_back(self, x)

    def front(self):
        return _gappa_swig.OneDVector_front(self)

    def back(self):
        return _gappa_swig.OneDVector_back(self)

    def assign(self, n, x):
        return _gappa_swig.OneDVector_assign(self, n, x)

    def resize(self, *args):
        return _gappa_swig.OneDVector_resize(self, *args)

    def insert(self, *args):
        return _gappa_swig.OneDVector_insert(self, *args)

    def reserve(self, n):
        return _gappa_swig.OneDVector_reserve(self, n)

    def capacity(self):
        return _gappa_swig.OneDVector_capacity(self)
    __swig_destroy__ = _gappa_swig.delete_OneDVector

# Register OneDVector in _gappa_swig:
_gappa_swig.OneDVector_swigregister(OneDVector)
class TwoDVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _gappa_swig.TwoDVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _gappa_swig.TwoDVector___nonzero__(self)

    def __bool__(self):
        return _gappa_swig.TwoDVector___bool__(self)

    def __len__(self):
        return _gappa_swig.TwoDVector___len__(self)

    def __getslice__(self, i, j):
        return _gappa_swig.TwoDVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _gappa_swig.TwoDVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _gappa_swig.TwoDVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _gappa_swig.TwoDVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _gappa_swig.TwoDVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _gappa_swig.TwoDVector___setitem__(self, *args)

    def pop(self):
        return _gappa_swig.TwoDVector_pop(self)

    def append(self, x):
        return _gappa_swig.TwoDVector_append(self, x)

    def empty(self):
        return _gappa_swig.TwoDVector_empty(self)

    def size(self):
        return _gappa_swig.TwoDVector_size(self)

    def swap(self, v):
        return _gappa_swig.TwoDVector_swap(self, v)

    def begin(self):
        return _gappa_swig.TwoDVector_begin(self)

    def end(self):
        return _gappa_swig.TwoDVector_end(self)

    def rbegin(self):
        return _gappa_swig.TwoDVector_rbegin(self)

    def rend(self):
        return _gappa_swig.TwoDVector_rend(self)

    def clear(self):
        return _gappa_swig.TwoDVector_clear(self)

    def get_allocator(self):
        return _gappa_swig.TwoDVector_get_allocator(self)

    def pop_back(self):
        return _gappa_swig.TwoDVector_pop_back(self)

    def erase(self, *args):
        return _gappa_swig.TwoDVector_erase(self, *args)

    def __init__(self, *args):
        _gappa_swig.TwoDVector_swiginit(self, _gappa_swig.new_TwoDVector(*args))

    def push_back(self, x):
        return _gappa_swig.TwoDVector_push_back(self, x)

    def front(self):
        return _gappa_swig.TwoDVector_front(self)

    def back(self):
        return _gappa_swig.TwoDVector_back(self)

    def assign(self, n, x):
        return _gappa_swig.TwoDVector_assign(self, n, x)

    def resize(self, *args):
        return _gappa_swig.TwoDVector_resize(self, *args)

    def insert(self, *args):
        return _gappa_swig.TwoDVector_insert(self, *args)

    def reserve(self, n):
        return _gappa_swig.TwoDVector_reserve(self, n)

    def capacity(self):
        return _gappa_swig.TwoDVector_capacity(self)
    __swig_destroy__ = _gappa_swig.delete_TwoDVector

# Register TwoDVector in _gappa_swig:
_gappa_swig.TwoDVector_swigregister(TwoDVector)
class Radiation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _gappa_swig.Radiation_swiginit(self, _gappa_swig.new_Radiation())
    __swig_destroy__ = _gappa_swig.delete_Radiation

    def SetProtons(self, PROTONS):
        return _gappa_swig.Radiation_SetProtons(self, PROTONS)

    def SetElectrons(self, ELECTRONS):
        return _gappa_swig.Radiation_SetElectrons(self, ELECTRONS)

    def SetElectronsIsotropic(self):
        return _gappa_swig.Radiation_SetElectronsIsotropic(self)

    def AddHadrons(self, Spectrum, Mass_number):
        return _gappa_swig.Radiation_AddHadrons(self, Spectrum, Mass_number)

    def GetHadrons(self, i):
        return _gappa_swig.Radiation_GetHadrons(self, i)

    def GetHadronMasses(self):
        return _gappa_swig.Radiation_GetHadronMasses(self)

    def SetAmbientMediumComposition(self, composition):
        return _gappa_swig.Radiation_SetAmbientMediumComposition(self, composition)

    def GetAmbientMediumComposition(self):
        return _gappa_swig.Radiation_GetAmbientMediumComposition(self)

    def ClearHadrons(self):
        return _gappa_swig.Radiation_ClearHadrons(self)

    def TestHadronLookup(self, i, e):
        return _gappa_swig.Radiation_TestHadronLookup(self, i, e)

    def UseKelner(self, kelner):
        return _gappa_swig.Radiation_UseKelner(self, kelner)

    def InelasticPPXSectionKelner(self, EP):
        return _gappa_swig.Radiation_InelasticPPXSectionKelner(self, EP)

    def UseKamae(self, kamae):
        return _gappa_swig.Radiation_UseKamae(self, kamae)

    def CalculateEpsilon(self, Tp, Mass):
        return _gappa_swig.Radiation_CalculateEpsilon(self, Tp, Mass)

    def NuNuXSection(self, ProjMass, TargetMass):
        return _gappa_swig.Radiation_NuNuXSection(self, ProjMass, TargetMass)

    def GetProtonVector(self):
        return _gappa_swig.Radiation_GetProtonVector(self)

    def GetElectronVector(self):
        return _gappa_swig.Radiation_GetElectronVector(self)

    def SetAmbientDensity(self, N):
        return _gappa_swig.Radiation_SetAmbientDensity(self, N)

    def GetAmbientDensity(self):
        return _gappa_swig.Radiation_GetAmbientDensity(self)

    def CalculateDifferentialGammaEmission(self, e, particletype):
        return _gappa_swig.Radiation_CalculateDifferentialGammaEmission(self, e, particletype)

    def CalculateDifferentialPhotonSpectrum(self, *args):
        return _gappa_swig.Radiation_CalculateDifferentialPhotonSpectrum(self, *args)

    def CalculateNeutrinoSpectrum(self, points):
        return _gappa_swig.Radiation_CalculateNeutrinoSpectrum(self, points)

    def ReturnDifferentialPhotonSpectrum(self, i, emin, emax, vec):
        return _gappa_swig.Radiation_ReturnDifferentialPhotonSpectrum(self, i, emin, emax, vec)

    def ReturnSED(self, i, emin, emax, vec):
        return _gappa_swig.Radiation_ReturnSED(self, i, emin, emax, vec)

    def SetBField(self, BFIELD):
        return _gappa_swig.Radiation_SetBField(self, BFIELD)

    def GetBField(self):
        return _gappa_swig.Radiation_GetBField(self)

    def SetDistance(self, d):
        return _gappa_swig.Radiation_SetDistance(self, d)

    def GetDifferentialICFlux(self, i=-1):
        return _gappa_swig.Radiation_GetDifferentialICFlux(self, i)

    def GetDifferentialSynchFlux(self):
        return _gappa_swig.Radiation_GetDifferentialSynchFlux(self)

    def GetDifferentialBremsFlux(self):
        return _gappa_swig.Radiation_GetDifferentialBremsFlux(self)

    def GetDifferentialPPFlux(self):
        return _gappa_swig.Radiation_GetDifferentialPPFlux(self)

    def GetDifferentialHadronFlux(self):
        return _gappa_swig.Radiation_GetDifferentialHadronFlux(self)

    def GetIntegralTotalFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralTotalFlux(self, emin, emax)

    def GetIntegralPPFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralPPFlux(self, emin, emax)

    def GetIntegralICFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralICFlux(self, emin, emax)

    def GetIntegralBremsstrahlungFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralBremsstrahlungFlux(self, emin, emax)

    def GetIntegralSynchrotronFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralSynchrotronFlux(self, emin, emax)

    def GetIntegralTotalEnergyFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralTotalEnergyFlux(self, emin, emax)

    def GetIntegralPPEnergyFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralPPEnergyFlux(self, emin, emax)

    def GetIntegralICEnergyFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralICEnergyFlux(self, emin, emax)

    def GetIntegralBremsstrahlungEnergyFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralBremsstrahlungEnergyFlux(self, emin, emax)

    def GetIntegralSynchrotronEnergyFlux(self, emin, emax):
        return _gappa_swig.Radiation_GetIntegralSynchrotronEnergyFlux(self, emin, emax)

    def CreateICLossLookup(self, bins=100):
        return _gappa_swig.Radiation_CreateICLossLookup(self, bins)

    def AddThermalTargetPhotons(self, T, energydens, steps=1000):
        return _gappa_swig.Radiation_AddThermalTargetPhotons(self, T, energydens, steps)

    def ResetWithThermalTargetPhotons(self, i, T, energydens, steps=1000):
        return _gappa_swig.Radiation_ResetWithThermalTargetPhotons(self, i, T, energydens, steps)

    def AddArbitraryTargetPhotons(self, PhotonArray):
        return _gappa_swig.Radiation_AddArbitraryTargetPhotons(self, PhotonArray)

    def ResetWithArbitraryTargetPhotons(self, i, PhotonArray):
        return _gappa_swig.Radiation_ResetWithArbitraryTargetPhotons(self, i, PhotonArray)

    def ImportTargetPhotonsFromFile(self, phFile):
        return _gappa_swig.Radiation_ImportTargetPhotonsFromFile(self, phFile)

    def ResetWithTargetPhotonsFromFile(self, i, phFile):
        return _gappa_swig.Radiation_ResetWithTargetPhotonsFromFile(self, i, phFile)

    def AddSSCTargetPhotons(self, R, steps=200):
        return _gappa_swig.Radiation_AddSSCTargetPhotons(self, R, steps)

    def ResetWithSSCTargetPhotons(self, i, R, steps=200):
        return _gappa_swig.Radiation_ResetWithSSCTargetPhotons(self, i, R, steps)

    def GetTargetPhotons(self, i=-1):
        return _gappa_swig.Radiation_GetTargetPhotons(self, i)

    def ClearTargetPhotons(self):
        return _gappa_swig.Radiation_ClearTargetPhotons(self)

    def Reset(self):
        return _gappa_swig.Radiation_Reset(self)

    def GetICLossLookup(self, i=-1):
        return _gappa_swig.Radiation_GetICLossLookup(self, i)

    def GetDistance(self):
        return _gappa_swig.Radiation_GetDistance(self)

    def GetTotalSpectrum(self, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetTotalSpectrum(self, emin, emax)

    def GetPPSpectrum(self, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetPPSpectrum(self, emin, emax)

    def GetBremsstrahlungSpectrum(self, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetBremsstrahlungSpectrum(self, emin, emax)

    def GetSynchrotronSpectrum(self, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetSynchrotronSpectrum(self, emin, emax)

    def GetTotalSED(self, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetTotalSED(self, emin, emax)

    def GetPPSED(self, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetPPSED(self, emin, emax)

    def GetBremsstrahlungSED(self, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetBremsstrahlungSED(self, emin, emax)

    def GetSynchrotronSED(self, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetSynchrotronSED(self, emin, emax)

    def GetICSpectrum(self, *args):
        return _gappa_swig.Radiation_GetICSpectrum(self, *args)

    def GetICSED(self, *args):
        return _gappa_swig.Radiation_GetICSED(self, *args)

    def GetHadronSpectrum(self, *args):
        return _gappa_swig.Radiation_GetHadronSpectrum(self, *args)

    def GetHadronSED(self, *args):
        return _gappa_swig.Radiation_GetHadronSED(self, *args)

    def ReturnNeutrinoSpectrum(self, vec):
        return _gappa_swig.Radiation_ReturnNeutrinoSpectrum(self, vec)

    def ReturnNeutrinoSED(self, vec):
        return _gappa_swig.Radiation_ReturnNeutrinoSED(self, vec)

    def ReturnHadronNeutrinoSpectrum(self, i, vec):
        return _gappa_swig.Radiation_ReturnHadronNeutrinoSpectrum(self, i, vec)

    def ReturnHadronNeutrinoSED(self, i, vec):
        return _gappa_swig.Radiation_ReturnHadronNeutrinoSED(self, i, vec)

    def GetNeutrinoSpectrum(self):
        return _gappa_swig.Radiation_GetNeutrinoSpectrum(self)

    def GetNeutrinoSED(self):
        return _gappa_swig.Radiation_GetNeutrinoSED(self)

    def GetNeutrinoSpectrumMuon(self):
        return _gappa_swig.Radiation_GetNeutrinoSpectrumMuon(self)

    def GetNeutrinoSpectrumElectron(self):
        return _gappa_swig.Radiation_GetNeutrinoSpectrumElectron(self)

    def GetNeutrinoSEDMuon(self):
        return _gappa_swig.Radiation_GetNeutrinoSEDMuon(self)

    def GetNeutrinoSEDElectron(self):
        return _gappa_swig.Radiation_GetNeutrinoSEDElectron(self)

    def GetProtonNeutrinoSpectrum(self):
        return _gappa_swig.Radiation_GetProtonNeutrinoSpectrum(self)

    def GetProtonNeutrinoSED(self):
        return _gappa_swig.Radiation_GetProtonNeutrinoSED(self)

    def GetProtonNeutrinoSpectrumMuon(self):
        return _gappa_swig.Radiation_GetProtonNeutrinoSpectrumMuon(self)

    def GetProtonNeutrinoSpectrumElectron(self):
        return _gappa_swig.Radiation_GetProtonNeutrinoSpectrumElectron(self)

    def GetProtonNeutrinoSEDMuon(self):
        return _gappa_swig.Radiation_GetProtonNeutrinoSEDMuon(self)

    def GetProtonNeutrinoSEDElectron(self):
        return _gappa_swig.Radiation_GetProtonNeutrinoSEDElectron(self)

    def GetHadronNeutrinoSpectrum(self, i):
        return _gappa_swig.Radiation_GetHadronNeutrinoSpectrum(self, i)

    def GetHadronNeutrinoSED(self, i):
        return _gappa_swig.Radiation_GetHadronNeutrinoSED(self, i)

    def GetHadronNeutrinoSpectrumMuon(self, i):
        return _gappa_swig.Radiation_GetHadronNeutrinoSpectrumMuon(self, i)

    def GetHadronNeutrinoSpectrumElectron(self, i):
        return _gappa_swig.Radiation_GetHadronNeutrinoSpectrumElectron(self, i)

    def GetHadronNeutrinoSEDMuon(self, i):
        return _gappa_swig.Radiation_GetHadronNeutrinoSEDMuon(self, i)

    def GetHadronNeutrinoSEDElectron(self, i):
        return _gappa_swig.Radiation_GetHadronNeutrinoSEDElectron(self, i)

    def Clone(self):
        return _gappa_swig.Radiation_Clone(self)

    def SetPPEmissionModel(self, PIMODEL):
        return _gappa_swig.Radiation_SetPPEmissionModel(self, PIMODEL)

    def GetPPEmissionModel(self):
        return _gappa_swig.Radiation_GetPPEmissionModel(self)

    def SetSynchrotronEmissionModel(self, SYNCHMODEL):
        return _gappa_swig.Radiation_SetSynchrotronEmissionModel(self, SYNCHMODEL)

    def GetSynchrotronEmissionModel(self):
        return _gappa_swig.Radiation_GetSynchrotronEmissionModel(self)

    def CheckSanityOfTargetPhotonLookup(self):
        return _gappa_swig.Radiation_CheckSanityOfTargetPhotonLookup(self)

    def GetProtonSED(self):
        return _gappa_swig.Radiation_GetProtonSED(self)

    def GetElectronSED(self):
        return _gappa_swig.Radiation_GetElectronSED(self)
    fUtils = property(_gappa_swig.Radiation_fUtils_get, _gappa_swig.Radiation_fUtils_set)

    def SetTargetPhotonAnisotropy(self, *args):
        return _gappa_swig.Radiation_SetTargetPhotonAnisotropy(self, *args)

    def GetTargetPhotonAnisotropy(self, i, phi, theta):
        return _gappa_swig.Radiation_GetTargetPhotonAnisotropy(self, i, phi, theta)

    def SetSynchrotronPitchAngle(self, synchangle):
        return _gappa_swig.Radiation_SetSynchrotronPitchAngle(self, synchangle)

    def SetInterpolationMethod(self, intermeth):
        return _gappa_swig.Radiation_SetInterpolationMethod(self, intermeth)

    def DiffPPXSection(self, Tp, Eg):
        return _gappa_swig.Radiation_DiffPPXSection(self, Tp, Eg)

    def MeanMultiplicity(self, Tp):
        return _gappa_swig.Radiation_MeanMultiplicity(self, Tp)

    def Amax(self, Tp):
        return _gappa_swig.Radiation_Amax(self, Tp)

    def F(self, Tp, Eg):
        return _gappa_swig.Radiation_F(self, Tp, Eg)

    def SigmaOnePi(self, Tp):
        return _gappa_swig.Radiation_SigmaOnePi(self, Tp)

    def SigmaTwoPi(self, Tp):
        return _gappa_swig.Radiation_SigmaTwoPi(self, Tp)

    def GetMaximumGammaEnergy(self, Tp):
        return _gappa_swig.Radiation_GetMaximumGammaEnergy(self, Tp)

    def GetMinimumGammaEnergy(self, Tp):
        return _gappa_swig.Radiation_GetMinimumGammaEnergy(self, Tp)

    def Epilabmax(self, Tp):
        return _gappa_swig.Radiation_Epilabmax(self, Tp)

    def InelasticPPXSectionKaf(self, Tp):
        return _gappa_swig.Radiation_InelasticPPXSectionKaf(self, Tp)

    def InclusivePPXSection(self, Tp):
        return _gappa_swig.Radiation_InclusivePPXSection(self, Tp)

    def ToggleQuietMode(self):
        return _gappa_swig.Radiation_ToggleQuietMode(self)

    def GetQuietMode(self):
        return _gappa_swig.Radiation_GetQuietMode(self)

    def ToggleVerboseMode(self):
        return _gappa_swig.Radiation_ToggleVerboseMode(self)

    def GetVerboseMode(self):
        return _gappa_swig.Radiation_GetVerboseMode(self)

    def ICEmissivityWrapper(self, e_ph, e_e, e_g):
        return _gappa_swig.Radiation_ICEmissivityWrapper(self, e_ph, e_e, e_g)

    def ICEmissivityAnisotropicWrapper(self, e_ph, e_e, e_g):
        return _gappa_swig.Radiation_ICEmissivityAnisotropicWrapper(self, e_ph, e_e, e_g)

    def GetTargetPhotonFieldEnergyDensity(self, i):
        return _gappa_swig.Radiation_GetTargetPhotonFieldEnergyDensity(self, i)

    def GetTargetFieldAnisotropyMap(self, i):
        return _gappa_swig.Radiation_GetTargetFieldAnisotropyMap(self, i)

    def ClearTargetPhotonField(self, i):
        return _gappa_swig.Radiation_ClearTargetPhotonField(self, i)

    def RemoveLastICTargetPhotonComponent(self):
        return _gappa_swig.Radiation_RemoveLastICTargetPhotonComponent(self)

    def SumTargetFields(self, bins, ISO=True):
        return _gappa_swig.Radiation_SumTargetFields(self, bins, ISO)

    def SumTargetFieldsAll(self, bins=1000):
        return _gappa_swig.Radiation_SumTargetFieldsAll(self, bins)

    def SumTargetFieldsIsotropic(self, bins=1000):
        return _gappa_swig.Radiation_SumTargetFieldsIsotropic(self, bins)

    def GetTargetFieldCount(self):
        return _gappa_swig.Radiation_GetTargetFieldCount(self)

    def SetICFastMode(self):
        return _gappa_swig.Radiation_SetICFastMode(self)

    def UnsetICFastMode(self):
        return _gappa_swig.Radiation_UnsetICFastMode(self)

    def SetSizePhotonField(self, i, size):
        return _gappa_swig.Radiation_SetSizePhotonField(self, i, size)

    def ClearPhotonFieldSize(self):
        return _gappa_swig.Radiation_ClearPhotonFieldSize(self)

    def GetSizePhotonField(self, *args):
        return _gappa_swig.Radiation_GetSizePhotonField(self, *args)

    def SetTargetFieldSpatialDep(self, i, SpatialDep):
        return _gappa_swig.Radiation_SetTargetFieldSpatialDep(self, i, SpatialDep)

    def GetTargetFieldSPatialDep(self, i):
        return _gappa_swig.Radiation_GetTargetFieldSPatialDep(self, i)

    def AverageSigmaGammaGamma(self, Eph1, Eph2):
        return _gappa_swig.Radiation_AverageSigmaGammaGamma(self, Eph1, Eph2)

    def SigmaGammaGamma(self, Eph1, Eph2, costheta):
        return _gappa_swig.Radiation_SigmaGammaGamma(self, Eph1, Eph2, costheta)

    def ComputeAbsCoeff(self, Egamma, target):
        return _gappa_swig.Radiation_ComputeAbsCoeff(self, Egamma, target)

    def ComputeOptDepth(self, Egamma, target, phsize):
        return _gappa_swig.Radiation_ComputeOptDepth(self, Egamma, target, phsize)

    def ComputeOptDepthIsotropic(self, Egamma, target, phsize):
        return _gappa_swig.Radiation_ComputeOptDepthIsotropic(self, Egamma, target, phsize)

    def ReturnAbsorbedSEDonFields(self, emin, emax, fields, size):
        return _gappa_swig.Radiation_ReturnAbsorbedSEDonFields(self, emin, emax, fields, size)

    def ReturnAbsorbedSpectrumOnFields(self, emin, emax, fields, size):
        return _gappa_swig.Radiation_ReturnAbsorbedSpectrumOnFields(self, emin, emax, fields, size)

    def GetTotalAbsorbedSpectrum(self, fields, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetTotalAbsorbedSpectrum(self, fields, emin, emax)

    def GetTotalAbsorbedSED(self, fields, emin=0., emax=0.):
        return _gappa_swig.Radiation_GetTotalAbsorbedSED(self, fields, emin, emax)

    def ReturnAbsorbedIntergratedFlux(self, emin, emax, ENERGYFLUX, fields, size):
        return _gappa_swig.Radiation_ReturnAbsorbedIntergratedFlux(self, emin, emax, ENERGYFLUX, fields, size)

    def GetIntegralTotalAbsEnergyFlux(self, emin, emax, fields):
        return _gappa_swig.Radiation_GetIntegralTotalAbsEnergyFlux(self, emin, emax, fields)

    def GetIntegralTotalAbsFlux(self, emin, emax, fields):
        return _gappa_swig.Radiation_GetIntegralTotalAbsFlux(self, emin, emax, fields)

    def SetLocalAmbientMediumComposition(self, *args):
        return _gappa_swig.Radiation_SetLocalAmbientMediumComposition(self, *args)

    def AddLocalCosmicRayModel(self, extragalactic=True, slope=2.65):
        return _gappa_swig.Radiation_AddLocalCosmicRayModel(self, extragalactic, slope)

    def AddCRModel(self, extragalactic=True, CREAM=False):
        return _gappa_swig.Radiation_AddCRModel(self, extragalactic, CREAM)

# Register Radiation in _gappa_swig:
_gappa_swig.Radiation_swigregister(Radiation)
class Particles(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _gappa_swig.Particles_swiginit(self, _gappa_swig.new_Particles())
    __swig_destroy__ = _gappa_swig.delete_Particles

    def SetMembers(self, t):
        return _gappa_swig.Particles_SetMembers(self, t)

    def CalculateProtonSpectrum(self, bins=100):
        return _gappa_swig.Particles_CalculateProtonSpectrum(self, bins)

    def CalculateElectronSpectrum(self, bins=100):
        return _gappa_swig.Particles_CalculateElectronSpectrum(self, bins)

    def CalculateProtonSpectrumInTimeInterval(self, T1, T2, bins=100):
        return _gappa_swig.Particles_CalculateProtonSpectrumInTimeInterval(self, T1, T2, bins)

    def CalculateElectronSpectrumInTimeInterval(self, T1, T2, bins=100, ICRESET=False):
        return _gappa_swig.Particles_CalculateElectronSpectrumInTimeInterval(self, T1, T2, bins, ICRESET)

    def SetType(self, type):
        return _gappa_swig.Particles_SetType(self, type)

    def EnergyLossRate(self, E):
        return _gappa_swig.Particles_EnergyLossRate(self, E)

    def SetIonization(self):
        return _gappa_swig.Particles_SetIonization(self)

    def UnsetIonization(self):
        return _gappa_swig.Particles_UnsetIonization(self)

    def SetAge(self, age):
        return _gappa_swig.Particles_SetAge(self, age)

    def GetAge(self):
        return _gappa_swig.Particles_GetAge(self)

    def GetLuminosity(self, age=0.):
        return _gappa_swig.Particles_GetLuminosity(self, age)

    def GetBField(self, age=0.):
        return _gappa_swig.Particles_GetBField(self, age)

    def GetAmbientDensity(self, age=0.):
        return _gappa_swig.Particles_GetAmbientDensity(self, age)

    def GetRadius(self, age=0.):
        return _gappa_swig.Particles_GetRadius(self, age)

    def GetExpansionVelocity(self, age=0.):
        return _gappa_swig.Particles_GetExpansionVelocity(self, age)

    def GetEmax(self, age=0.):
        return _gappa_swig.Particles_GetEmax(self, age)

    def GetEscapeTime(self, *args):
        return _gappa_swig.Particles_GetEscapeTime(self, *args)

    def ToggleDebugging(self):
        return _gappa_swig.Particles_ToggleDebugging(self)

    def SetICLossLookup(self, ICLOSSLOOKUP):
        return _gappa_swig.Particles_SetICLossLookup(self, ICLOSSLOOKUP)

    def ExtendICLossLookup(self, ICLOSSLOOKUP):
        return _gappa_swig.Particles_ExtendICLossLookup(self, ICLOSSLOOKUP)

    def ExtendLuminosityLookup(self, LUMLOOKUP):
        return _gappa_swig.Particles_ExtendLuminosityLookup(self, LUMLOOKUP)

    def ExtendAmbientDensityLookup(self, NLOOKUP):
        return _gappa_swig.Particles_ExtendAmbientDensityLookup(self, NLOOKUP)

    def ExtendBFieldLookup(self, BFIELDLOOKUP):
        return _gappa_swig.Particles_ExtendBFieldLookup(self, BFIELDLOOKUP)

    def ExtendEmaxLookup(self, EMAXLOOKUP):
        return _gappa_swig.Particles_ExtendEmaxLookup(self, EMAXLOOKUP)

    def ExtendEscapeTimeLookup(self, ESCTIMELOOKUP):
        return _gappa_swig.Particles_ExtendEscapeTimeLookup(self, ESCTIMELOOKUP)

    def ExtendRadiusLookup(self, RLOOKUP):
        return _gappa_swig.Particles_ExtendRadiusLookup(self, RLOOKUP)

    def ExtendVelocityLookup(self, VLOOKUP):
        return _gappa_swig.Particles_ExtendVelocityLookup(self, VLOOKUP)

    def GetLuminosityLookup(self):
        return _gappa_swig.Particles_GetLuminosityLookup(self)

    def GetEmaxLookup(self):
        return _gappa_swig.Particles_GetEmaxLookup(self)

    def GetBFieldLookup(self):
        return _gappa_swig.Particles_GetBFieldLookup(self)

    def GetRadiusLookup(self):
        return _gappa_swig.Particles_GetRadiusLookup(self)

    def GetVelocityLookup(self):
        return _gappa_swig.Particles_GetVelocityLookup(self)

    def GetEnergyLossRate(self, *args):
        return _gappa_swig.Particles_GetEnergyLossRate(self, *args)

    def GetCoolingTimeScale(self, *args):
        return _gappa_swig.Particles_GetCoolingTimeScale(self, *args)

    def GetInjectionSpectrum(self, epoints, age=0.):
        return _gappa_swig.Particles_GetInjectionSpectrum(self, epoints, age)

    def GetInjectionSED(self, epoints, age=0.):
        return _gappa_swig.Particles_GetInjectionSED(self, epoints, age)

    def GetQuantityVector(self, epoints, age, mode):
        return _gappa_swig.Particles_GetQuantityVector(self, epoints, age, mode)

    def GetEnergyBins(self):
        return _gappa_swig.Particles_GetEnergyBins(self)

    def GetParticleSpectrum(self):
        return _gappa_swig.Particles_GetParticleSpectrum(self)

    def GetEscapeVector(self):
        return _gappa_swig.Particles_GetEscapeVector(self)

    def SetTmin(self, TMIN):
        return _gappa_swig.Particles_SetTmin(self, TMIN)

    def SetBField(self, *args):
        return _gappa_swig.Particles_SetBField(self, *args)

    def SetAmbientDensity(self, *args):
        return _gappa_swig.Particles_SetAmbientDensity(self, *args)

    def SetRadius(self, *args):
        return _gappa_swig.Particles_SetRadius(self, *args)

    def SetExpansionVelocity(self, *args):
        return _gappa_swig.Particles_SetExpansionVelocity(self, *args)

    def SetCutOffFactor(self, CUTOFFFACTOR):
        return _gappa_swig.Particles_SetCutOffFactor(self, CUTOFFFACTOR)

    def GetCutOffFactor(self):
        return _gappa_swig.Particles_GetCutOffFactor(self)

    def SetEnergyMarginFactor(self, ENERGYMARGINFACTOR):
        return _gappa_swig.Particles_SetEnergyMarginFactor(self, ENERGYMARGINFACTOR)

    def ToggleSharpEnergyCut(self):
        return _gappa_swig.Particles_ToggleSharpEnergyCut(self)

    def UnToggleSharpEnergyCut(self):
        return _gappa_swig.Particles_UnToggleSharpEnergyCut(self)

    def SetTminInternal(self, TMININTERNAL):
        return _gappa_swig.Particles_SetTminInternal(self, TMININTERNAL)

    def GetTminInternal(self):
        return _gappa_swig.Particles_GetTminInternal(self)

    def GetEnergyTrajectoryVector(self):
        return _gappa_swig.Particles_GetEnergyTrajectoryVector(self)

    def GetParticleSED(self):
        return _gappa_swig.Particles_GetParticleSED(self)

    def GetGrid(self):
        return _gappa_swig.Particles_GetGrid(self)

    def GetParticleEnergyContent(self, E1=0., E2=0.):
        return _gappa_swig.Particles_GetParticleEnergyContent(self, E1, E2)

    def SetLuminosity(self, *args):
        return _gappa_swig.Particles_SetLuminosity(self, *args)

    def SetCriticalMinEnergyForGridSolver(self, eminint):
        return _gappa_swig.Particles_SetCriticalMinEnergyForGridSolver(self, eminint)

    def SetIntegratorMemory(self, mode):
        return _gappa_swig.Particles_SetIntegratorMemory(self, mode)

    def SetInterpolationMethod(self, intermeth):
        return _gappa_swig.Particles_SetInterpolationMethod(self, intermeth)

    def SetCustomTimeEnergyLookup(self, vCustom, mode):
        return _gappa_swig.Particles_SetCustomTimeEnergyLookup(self, vCustom, mode)

    def SetCustomEnergylookup(self, vCustom, mode):
        return _gappa_swig.Particles_SetCustomEnergylookup(self, vCustom, mode)

    def SetCustomInjectionSpectrum(self, vSpectrum):
        return _gappa_swig.Particles_SetCustomInjectionSpectrum(self, vSpectrum)

    def SetCustomInjectionSpectrumTimeEvolution(self, *args):
        return _gappa_swig.Particles_SetCustomInjectionSpectrumTimeEvolution(self, *args)

    def SetConstantEscapeTime(self, EscapeTime):
        return _gappa_swig.Particles_SetConstantEscapeTime(self, EscapeTime)

    def SetTimeDependentEscapeTime(self, vEsc):
        return _gappa_swig.Particles_SetTimeDependentEscapeTime(self, vEsc)

    def SetEnergyDependentEscapeTime(self, ESCTIMELOOKUP):
        return _gappa_swig.Particles_SetEnergyDependentEscapeTime(self, ESCTIMELOOKUP)

    def SetTimeAndEnergyDependentEscapeTime(self, *args):
        return _gappa_swig.Particles_SetTimeAndEnergyDependentEscapeTime(self, *args)

    def SetSolverMethod(self, method):
        return _gappa_swig.Particles_SetSolverMethod(self, method)

    def ToggleQuietMode(self):
        return _gappa_swig.Particles_ToggleQuietMode(self)

    def GetQuietMode(self):
        return _gappa_swig.Particles_GetQuietMode(self)

    def AddThermalTargetPhotons(self, T, edens, steps=200):
        return _gappa_swig.Particles_AddThermalTargetPhotons(self, T, edens, steps)

    def ResetWithThermalTargetPhotons(self, i, T, edens, steps=200):
        return _gappa_swig.Particles_ResetWithThermalTargetPhotons(self, i, T, edens, steps)

    def AddArbitraryTargetPhotons(self, PhotonArray):
        return _gappa_swig.Particles_AddArbitraryTargetPhotons(self, PhotonArray)

    def ResetWithArbitraryTargetPhotons(self, i, PhotonArray):
        return _gappa_swig.Particles_ResetWithArbitraryTargetPhotons(self, i, PhotonArray)

    def ImportTargetPhotonsFromFile(self, phFile):
        return _gappa_swig.Particles_ImportTargetPhotonsFromFile(self, phFile)

    def ResetWithTargetPhotonsFromFile(self, i, phFile):
        return _gappa_swig.Particles_ResetWithTargetPhotonsFromFile(self, i, phFile)

    def AddSSCTargetPhotons(self, steps=100):
        return _gappa_swig.Particles_AddSSCTargetPhotons(self, steps)

    def ResetWithSSCTargetPhotons(self, i, steps=100):
        return _gappa_swig.Particles_ResetWithSSCTargetPhotons(self, i, steps)

    def GetICLossLookup(self, i=-1):
        return _gappa_swig.Particles_GetICLossLookup(self, i)

    def GetTargetPhotonFieldEnergyDensity(self, i):
        return _gappa_swig.Particles_GetTargetPhotonFieldEnergyDensity(self, i)

    def CheckSanityOfTargetPhotonLookup(self):
        return _gappa_swig.Particles_CheckSanityOfTargetPhotonLookup(self)

    def GetTargetPhotons(self, i=-1):
        return _gappa_swig.Particles_GetTargetPhotons(self, i)

    def ClearTargetPhotons(self):
        return _gappa_swig.Particles_ClearTargetPhotons(self)

    def SetSynchrotronEmissionModel(self, SYNCHMODEL):
        return _gappa_swig.Particles_SetSynchrotronEmissionModel(self, SYNCHMODEL)

    def CalculateSSCEquilibrium(self, tolerance=5e-2, bins=100):
        return _gappa_swig.Particles_CalculateSSCEquilibrium(self, tolerance, bins)

    def SetFastIteration(self):
        return _gappa_swig.Particles_SetFastIteration(self)

    def SetPreciseIteration(self):
        return _gappa_swig.Particles_SetPreciseIteration(self)

    def GetTargetFieldCount(self):
        return _gappa_swig.Particles_GetTargetFieldCount(self)

    def SetEmin(self, EMIN, ONLYFORNORMALISATION=False):
        return _gappa_swig.Particles_SetEmin(self, EMIN, ONLYFORNORMALISATION)

    def SetEmax(self, *args):
        return _gappa_swig.Particles_SetEmax(self, *args)

    def SetSpectralIndex(self, spectralindex):
        return _gappa_swig.Particles_SetSpectralIndex(self, spectralindex)

    def SetLowSpectralIndex(self, spectralindex2):
        return _gappa_swig.Particles_SetLowSpectralIndex(self, spectralindex2)

    def SetBreakEnergy(self, ebreak):
        return _gappa_swig.Particles_SetBreakEnergy(self, ebreak)

    def SetSourceExpansionSpeed(self, v):
        return _gappa_swig.Particles_SetSourceExpansionSpeed(self, v)

    def GetSpeed(self):
        return _gappa_swig.Particles_GetSpeed(self)

    def SetEmaxLookup(self, EMAXLOOKUP):
        return _gappa_swig.Particles_SetEmaxLookup(self, EMAXLOOKUP)

    def SetAmbientDensityLookup(self, NLOOKUP):
        return _gappa_swig.Particles_SetAmbientDensityLookup(self, NLOOKUP)

    def SetLuminosityLookup(self, LUMLOOKUP):
        return _gappa_swig.Particles_SetLuminosityLookup(self, LUMLOOKUP)

    def SetBFieldLookup(self, BFIELDLOOKUP):
        return _gappa_swig.Particles_SetBFieldLookup(self, BFIELDLOOKUP)

    def SetEscapeTimeLookup(self, ESCTIMELOOKUP):
        return _gappa_swig.Particles_SetEscapeTimeLookup(self, ESCTIMELOOKUP)

    def SetRadiusLookup(self, RADIUSLOOKUP):
        return _gappa_swig.Particles_SetRadiusLookup(self, RADIUSLOOKUP)

    def SetVelocityLookup(self, VELOCITYLOOKUP):
        return _gappa_swig.Particles_SetVelocityLookup(self, VELOCITYLOOKUP)

    def SetEnergyBins(self, EBINS):
        return _gappa_swig.Particles_SetEnergyBins(self, EBINS)

# Register Particles in _gappa_swig:
_gappa_swig.Particles_swigregister(Particles)
TeV_to_erg = _gappa_swig.TeV_to_erg
GeV_to_erg = _gappa_swig.GeV_to_erg
eV_to_erg = _gappa_swig.eV_to_erg
erg_to_TeV = _gappa_swig.erg_to_TeV
sigma_T = _gappa_swig.sigma_T
e_radius = _gappa_swig.e_radius
pc_to_cm = _gappa_swig.pc_to_cm
kpc_to_cm = _gappa_swig.kpc_to_cm
AU_to_cm = _gappa_swig.AU_to_cm
m_p_g = _gappa_swig.m_p_g
yr_to_sec = _gappa_swig.yr_to_sec
mSol = _gappa_swig.mSol
m_e = _gappa_swig.m_e
kb = _gappa_swig.kb
m_p = _gappa_swig.m_p
m_pi = _gappa_swig.m_pi
pi = _gappa_swig.pi
c_speed = _gappa_swig.c_speed
el_charge = _gappa_swig.el_charge
eRadius = _gappa_swig.eRadius
hp = _gappa_swig.hp
fineStructConst = _gappa_swig.fineStructConst
h_to_sec = _gappa_swig.h_to_sec
pc_to_lyr = _gappa_swig.pc_to_lyr
ln10 = _gappa_swig.ln10

def sortcriterionfirstcolumn(i, j):
    return _gappa_swig.sortcriterionfirstcolumn(i, j)

def sortcriterionsecondcolumn(i, j):
    return _gappa_swig.sortcriterionsecondcolumn(i, j)
class Utils(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, DRAWLOGO=False):
        _gappa_swig.Utils_swiginit(self, _gappa_swig.new_Utils(DRAWLOGO))
    __swig_destroy__ = _gappa_swig.delete_Utils

    def ReadParameterFile(self, inputname, parameter_names, files_names, parameter_values, files):
        return _gappa_swig.Utils_ReadParameterFile(self, inputname, parameter_names, files_names, parameter_values, files)

    def DrawGamera(self):
        return _gappa_swig.Utils_DrawGamera(self)

    def DrawGappa(self):
        return _gappa_swig.Utils_DrawGappa(self)

    def WriteOut(self, sp, outname):
        return _gappa_swig.Utils_WriteOut(self, sp, outname)

    def ReadIn(self, inname, sp):
        return _gappa_swig.Utils_ReadIn(self, inname, sp)

    def Random(self):
        return _gappa_swig.Utils_Random(self)

    def UniformRandom(self, x_min, x_max, n):
        return _gappa_swig.Utils_UniformRandom(self, x_min, x_max, n)

    def LinearRandom(self, slope, x_min, x_max, n):
        return _gappa_swig.Utils_LinearRandom(self, slope, x_min, x_max, n)

    def PowerLawRandom(self, index, x_min, x_max, n):
        return _gappa_swig.Utils_PowerLawRandom(self, index, x_min, x_max, n)

    def GaussianRandom(self, width, offset, n):
        return _gappa_swig.Utils_GaussianRandom(self, width, offset, n)

    def SignRandom(self, n):
        return _gappa_swig.Utils_SignRandom(self, n)

    def ExponentialRandom(self, ind_norm, x_min, x_max, n):
        return _gappa_swig.Utils_ExponentialRandom(self, ind_norm, x_min, x_max, n)

    def CustomFunctionRandom(self, f, n, xmin=0., xmax=0.):
        return _gappa_swig.Utils_CustomFunctionRandom(self, f, n, xmin, xmax)

    def CustomFunctionRandom2D(self, f, n, xmin=0., xmax=0., ymin=0., ymax=0.):
        return _gappa_swig.Utils_CustomFunctionRandom2D(self, f, n, xmin, xmax, ymin, ymax)

    def Integrate(self, f, xmin=0., xmax=0.):
        return _gappa_swig.Utils_Integrate(self, f, xmin, xmax)

    def IntegratedProfile(self, f):
        return _gappa_swig.Utils_IntegratedProfile(self, f)

    def GSLsplineFromTwoDVector(self, v):
        return _gappa_swig.Utils_GSLsplineFromTwoDVector(self, v)

    def SortTwoDVector(self, v, column):
        return _gappa_swig.Utils_SortTwoDVector(self, v, column)

    def TwoDVectorPushBack(self, *args):
        return _gappa_swig.Utils_TwoDVectorPushBack(self, *args)

    def ZipTwoOneDVectors(self, x, y):
        return _gappa_swig.Utils_ZipTwoOneDVectors(self, x, y)

    def EvalSpline(self, x, s, a, t, l):
        return _gappa_swig.Utils_EvalSpline(self, x, s, a, t, l)

    def SetInterpolationMethod(self, intermeth):
        return _gappa_swig.Utils_SetInterpolationMethod(self, intermeth)

    def Clear2DVector(self, v):
        return _gappa_swig.Utils_Clear2DVector(self, v)

    def Clear3DVector(self, v):
        return _gappa_swig.Utils_Clear3DVector(self, v)

    def VectorAxisLogarithm(self, v, column):
        return _gappa_swig.Utils_VectorAxisLogarithm(self, v, column)

    def VectorAxisPow10(self, v, column):
        return _gappa_swig.Utils_VectorAxisPow10(self, v, column)

    def TwoDsplineFromTwoDVector(self, v, xmin, xmax, ymin, ymax):
        return _gappa_swig.Utils_TwoDsplineFromTwoDVector(self, v, xmin, xmax, ymin, ymax)

    def SetInternal1DSpline(self, v):
        return _gappa_swig.Utils_SetInternal1DSpline(self, v)

    def SetInternal2DSpline(self, v):
        return _gappa_swig.Utils_SetInternal2DSpline(self, v)

    def EvalInternal1DSpline(self, x):
        return _gappa_swig.Utils_EvalInternal1DSpline(self, x)

    def EvalInternal2DSpline(self, x, y):
        return _gappa_swig.Utils_EvalInternal2DSpline(self, x, y)

    def EnergyContent(self, f, emin=0., emax=0.):
        return _gappa_swig.Utils_EnergyContent(self, f, emin, emax)

    def EnergyContentFast(self, f):
        return _gappa_swig.Utils_EnergyContentFast(self, f)

    def MeshgridToTwoDVector(self, x, y, mesh):
        return _gappa_swig.Utils_MeshgridToTwoDVector(self, x, y, mesh)

    def GetVectorMinMax(self, v, axis):
        return _gappa_swig.Utils_GetVectorMinMax(self, v, axis)

    def GetVectorMinMaxIndices(self, v, axis):
        return _gappa_swig.Utils_GetVectorMinMaxIndices(self, v, axis)

    def ToggleQuietMode(self):
        return _gappa_swig.Utils_ToggleQuietMode(self)

    def GetQuietMode(self):
        return _gappa_swig.Utils_GetQuietMode(self)

    def RemoveZeroEntries(self, v):
        return _gappa_swig.Utils_RemoveZeroEntries(self, v)

    def TwoDVectorFabs(self, v):
        return _gappa_swig.Utils_TwoDVectorFabs(self, v)

    def RotateVector(self, v, p1, p2):
        return _gappa_swig.Utils_RotateVector(self, v, p1, p2)

    def Gaussian1D(self, x, sigma, mu=0., norm=0.):
        return _gappa_swig.Utils_Gaussian1D(self, x, sigma, mu, norm)

    def LogisticsFunction(self, z, h, w):
        return _gappa_swig.Utils_LogisticsFunction(self, z, h, w)

    def Norm(self, v):
        return _gappa_swig.Utils_Norm(self, v)

# Register Utils in _gappa_swig:
_gappa_swig.Utils_swigregister(Utils)
class Astro(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _gappa_swig.Astro_swiginit(self, _gappa_swig.new_Astro())
    __swig_destroy__ = _gappa_swig.delete_Astro

    def SetGalacticReferencePoint(self, xyz_ref):
        return _gappa_swig.Astro_SetGalacticReferencePoint(self, xyz_ref)

    def DisableArm(self, arm):
        return _gappa_swig.Astro_DisableArm(self, arm)

    def EnableArm(self, arm):
        return _gappa_swig.Astro_EnableArm(self, arm)

    def RandomSalpeterInitialMass(self):
        return _gappa_swig.Astro_RandomSalpeterInitialMass(self)

    def MainSequenceBubbleRadius(self, mDotMS, vMSWind, timeMS, n, initialMass):
        return _gappa_swig.Astro_MainSequenceBubbleRadius(self, mDotMS, vMSWind, timeMS, n, initialMass)

    def CalculateMSBubbleDensity(self, mDotMS, vMSWind, timeMS, n, bubbleRadius):
        return _gappa_swig.Astro_CalculateMSBubbleDensity(self, mDotMS, vMSWind, timeMS, n, bubbleRadius)

    def CalculateTimeOnMainSequence(self, initialMass):
        return _gappa_swig.Astro_CalculateTimeOnMainSequence(self, initialMass)

    def CalculateMSMassLuminosity(self, initialMass):
        return _gappa_swig.Astro_CalculateMSMassLuminosity(self, initialMass)

    def CalculateMSWindSpeed(self, initialMass):
        return _gappa_swig.Astro_CalculateMSWindSpeed(self, initialMass)

    def CalculateRGWRadius(self, pBubble, mDotRGW, vRGWind):
        return _gappa_swig.Astro_CalculateRGWRadius(self, pBubble, mDotRGW, vRGWind)

    def HTotalDensity(self, x, y, z):
        return _gappa_swig.Astro_HTotalDensity(self, x, y, z)

    def HIDensity(self, x, y, z, MODULATE=True):
        return _gappa_swig.Astro_HIDensity(self, x, y, z, MODULATE)

    def H2Density(self, x, y, z, MODULATE=True):
        return _gappa_swig.Astro_H2Density(self, x, y, z, MODULATE)

    def HIIDensity(self, x, y, z, MODULATE=True):
        return _gappa_swig.Astro_HIIDensity(self, x, y, z, MODULATE)

    def H_I_2_CMZ(self, x, y, z, H_c, norm):
        return _gappa_swig.Astro_H_I_2_CMZ(self, x, y, z, H_c, norm)

    def H_I_2_InnerDisk(self, x, y, z, H_d, norm):
        return _gappa_swig.Astro_H_I_2_InnerDisk(self, x, y, z, H_d, norm)

    def H2CMZ(self, x, y, z):
        return _gappa_swig.Astro_H2CMZ(self, x, y, z)

    def HICMZ(self, x, y, z):
        return _gappa_swig.Astro_HICMZ(self, x, y, z)

    def H2InnerDisk(self, x, y, z):
        return _gappa_swig.Astro_H2InnerDisk(self, x, y, z)

    def HIIThickDisk(self, x, y, z):
        return _gappa_swig.Astro_HIIThickDisk(self, x, y, z)

    def HIIThinDisk(self, x, y, z):
        return _gappa_swig.Astro_HIIThinDisk(self, x, y, z)

    def HIInnerDisk(self, x, y, z):
        return _gappa_swig.Astro_HIInnerDisk(self, x, y, z)

    def WarmHIIDensity(self, x, y, z):
        return _gappa_swig.Astro_WarmHIIDensity(self, x, y, z)

    def HotHIIDensity(self, x, y, z):
        return _gappa_swig.Astro_HotHIIDensity(self, x, y, z)

    def VeryHotHIIDensity(self, x, y, z):
        return _gappa_swig.Astro_VeryHotHIIDensity(self, x, y, z)

    def GravitationalPotential(self, r, z):
        return _gappa_swig.Astro_GravitationalPotential(self, r, z)

    def CalculateHINorm(self, R):
        return _gappa_swig.Astro_CalculateHINorm(self, R)

    def CalculateH2Norm(self, R):
        return _gappa_swig.Astro_CalculateH2Norm(self, R)

    def GetHIColumnDensity(self, R):
        return _gappa_swig.Astro_GetHIColumnDensity(self, R)

    def GetH2ColumnDensity(self, R):
        return _gappa_swig.Astro_GetH2ColumnDensity(self, R)

    def GetHIFWHM(self, R):
        return _gappa_swig.Astro_GetHIFWHM(self, R)

    def GetH2FWHM(self, R):
        return _gappa_swig.Astro_GetH2FWHM(self, R)

    def ModulateGasDensityWithSpirals(self, n, x, y, z):
        return _gappa_swig.Astro_ModulateGasDensityWithSpirals(self, n, x, y, z)

    def GetTotalHDensityFerriere(self, xyz):
        return _gappa_swig.Astro_GetTotalHDensityFerriere(self, xyz)

    def GetH2DensityFerriere(self, xyz):
        return _gappa_swig.Astro_GetH2DensityFerriere(self, xyz)

    def GetNeutralHDensityFerriere(self, xyz):
        return _gappa_swig.Astro_GetNeutralHDensityFerriere(self, xyz)

    def GetHIIDensityFerriere(self, xyz):
        return _gappa_swig.Astro_GetHIIDensityFerriere(self, xyz)

    def GetCMDensityFerriere(self, xyz):
        return _gappa_swig.Astro_GetCMDensityFerriere(self, xyz)

    def GetWNMDensityFerriere(self, xyz):
        return _gappa_swig.Astro_GetWNMDensityFerriere(self, xyz)

    def GetWIMDensityFerriere(self, xyz):
        return _gappa_swig.Astro_GetWIMDensityFerriere(self, xyz)

    def GetHIMDensityFerriere(self, xyz):
        return _gappa_swig.Astro_GetHIMDensityFerriere(self, xyz)

    def GetH2DensityCMZFerriere(self, xyz):
        return _gappa_swig.Astro_GetH2DensityCMZFerriere(self, xyz)

    def GetH2DensityDiskFerriere(self, xyz):
        return _gappa_swig.Astro_GetH2DensityDiskFerriere(self, xyz)

    def GetHIDensityCMZFerriere(self, xyz):
        return _gappa_swig.Astro_GetHIDensityCMZFerriere(self, xyz)

    def GetHIDensityDiskFerriere(self, xyz):
        return _gappa_swig.Astro_GetHIDensityDiskFerriere(self, xyz)

    def GetHIIDensityWIMFerriere(self, xyz):
        return _gappa_swig.Astro_GetHIIDensityWIMFerriere(self, xyz)

    def GetHIIDensityHIMFerriere(self, xyz):
        return _gappa_swig.Astro_GetHIIDensityHIMFerriere(self, xyz)

    def GetHIIDensityVHIMFerriere(self, xyz):
        return _gappa_swig.Astro_GetHIIDensityVHIMFerriere(self, xyz)

    def phi_RZ(self, r, z):
        return _gappa_swig.Astro_phi_RZ(self, r, z)

    def GetCartesian(self, *args):
        return _gappa_swig.Astro_GetCartesian(self, *args)

    def GetCartesianPositions(self, lbr, xyzobs):
        return _gappa_swig.Astro_GetCartesianPositions(self, lbr, xyzobs)

    def GetGalactic(self, *args):
        return _gappa_swig.Astro_GetGalactic(self, *args)

    def GetGalacticPositions(self, xyz, xyzref):
        return _gappa_swig.Astro_GetGalacticPositions(self, xyz, xyzref)

    def RotateCoordinates(self, x, y, z, phi, theta, psi):
        return _gappa_swig.Astro_RotateCoordinates(self, x, y, z, phi, theta, psi)

    def RandomTangentialShift(self, r, width, x, y):
        return _gappa_swig.Astro_RandomTangentialShift(self, r, width, x, y)

    def RandomGaussianShift(self, r, width, x, y):
        return _gappa_swig.Astro_RandomGaussianShift(self, r, width, x, y)

    def ApparentSize(self, size, lbr):
        return _gappa_swig.Astro_ApparentSize(self, size, lbr)

    def GetApparentSizes(self, sizes, lbr):
        return _gappa_swig.Astro_GetApparentSizes(self, sizes, lbr)

    def GetRandomArm(self, r):
        return _gappa_swig.Astro_GetRandomArm(self, r)

    def Bar(self, r, x, y):
        return _gappa_swig.Astro_Bar(self, r, x, y)

    def Disk(self, r, x, y):
        return _gappa_swig.Astro_Disk(self, r, x, y)

    def LinearSurfDens(self, x, par):
        return _gappa_swig.Astro_LinearSurfDens(self, x, par)

    def TaylorCordesSpiral(self, r, arm, x, y):
        return _gappa_swig.Astro_TaylorCordesSpiral(self, r, arm, x, y)

    def TaylorCordesSpiralAngular(self, theta, arm):
        return _gappa_swig.Astro_TaylorCordesSpiralAngular(self, theta, arm)

    def ValleeSpiral(self, r, arm, x, y):
        return _gappa_swig.Astro_ValleeSpiral(self, r, arm, x, y)

    def ValleeSpiralAngular(self, theta, arm):
        return _gappa_swig.Astro_ValleeSpiralAngular(self, theta, arm)

    def GetRandomZValue(self, scaleHeight):
        return _gappa_swig.Astro_GetRandomZValue(self, scaleHeight)

    def GetRandomGalactocentricRadii(self, n):
        return _gappa_swig.Astro_GetRandomGalactocentricRadii(self, n)

    def GalacticPositionXY(self, r, arm, x, y):
        return _gappa_swig.Astro_GalacticPositionXY(self, r, arm, x, y)

    def PositionOnSpiralArmAngular(self, theta, arm, x, y):
        return _gappa_swig.Astro_PositionOnSpiralArmAngular(self, theta, arm, x, y)

    def GetDistanceToNearestSpiralArm(self, x, y, DistanceToClosestArm, ClosestArm):
        return _gappa_swig.Astro_GetDistanceToNearestSpiralArm(self, x, y, DistanceToClosestArm, ClosestArm)

    def GetDistanceToGivenSpiralArm(self, x, y, arm):
        return _gappa_swig.Astro_GetDistanceToGivenSpiralArm(self, x, y, arm)

    def DiceGalacticPositions(self, i):
        return _gappa_swig.Astro_DiceGalacticPositions(self, i)

    def GetRMax(self):
        return _gappa_swig.Astro_GetRMax(self)

    def SetSpiralArmModel(self, centralstructuremodel):
        return _gappa_swig.Astro_SetSpiralArmModel(self, centralstructuremodel)

    def SetCentralStructureModel(self, centralstructuremodel):
        return _gappa_swig.Astro_SetCentralStructureModel(self, centralstructuremodel)

    def SetSurfaceDensityModel(self, surfacedensitymodel):
        return _gappa_swig.Astro_SetSurfaceDensityModel(self, surfacedensitymodel)

    def SetMainSequenceBubbleModel(self, msbubblemodel):
        return _gappa_swig.Astro_SetMainSequenceBubbleModel(self, msbubblemodel)

    def SetScaleHeight(self, SCALEHEIGHT):
        return _gappa_swig.Astro_SetScaleHeight(self, SCALEHEIGHT)

    def SetArmWidth(self, ARMWIDTH):
        return _gappa_swig.Astro_SetArmWidth(self, ARMWIDTH)

    def CreateDensityProfile(self, pars, rmin=1.e-3, rmax=1.e3):
        return _gappa_swig.Astro_CreateDensityProfile(self, pars, rmin, rmax)

    def EvalTaylorCordesArmTheta(self, r, arm):
        return _gappa_swig.Astro_EvalTaylorCordesArmTheta(self, r, arm)

    def EvalTaylorCordesArmGalactocentricRadius(self, theta, arm):
        return _gappa_swig.Astro_EvalTaylorCordesArmGalactocentricRadius(self, theta, arm)

    def CaseBhattacharyaProfile(self, r):
        return _gappa_swig.Astro_CaseBhattacharyaProfile(self, r)

    def IusifovKucukProfile(self, r):
        return _gappa_swig.Astro_IusifovKucukProfile(self, r)

    def CalculateThinShellApproximation(self, dProfile, E, AdiabIndex=1.333, tmin=1.e-2, tmax=1.e4, steps=200):
        return _gappa_swig.Astro_CalculateThinShellApproximation(self, dProfile, E, AdiabIndex, tmin, tmax, steps)

    def CalculateTrueloveMcKeeSolution(self, pars, tmin=1.e-2, tmax=1.e4, steps=200):
        return _gappa_swig.Astro_CalculateTrueloveMcKeeSolution(self, pars, tmin, tmax, steps)

    def CalculateTangChevalierSolution(self, pars, tmin=1.e-2, tmax=1.e4, steps=200):
        return _gappa_swig.Astro_CalculateTangChevalierSolution(self, pars, tmin, tmax, steps)

    def ThinShellRadiusAndSpeed(self, t):
        return _gappa_swig.Astro_ThinShellRadiusAndSpeed(self, t)

    def TrueloveMcKeeRadiusAndSpeedForward(self, t):
        return _gappa_swig.Astro_TrueloveMcKeeRadiusAndSpeedForward(self, t)

    def TrueloveMcKeeRadiusAndSpeedReverse(self, t):
        return _gappa_swig.Astro_TrueloveMcKeeRadiusAndSpeedReverse(self, t)

    def GetForwardShockRadiusEvolution(self):
        return _gappa_swig.Astro_GetForwardShockRadiusEvolution(self)

    def GetForwardShockVelocityEvolution(self):
        return _gappa_swig.Astro_GetForwardShockVelocityEvolution(self)

    def GetReverseShockRadiusEvolution(self):
        return _gappa_swig.Astro_GetReverseShockRadiusEvolution(self)

    def GetReverseShockVelocityEvolution(self):
        return _gappa_swig.Astro_GetReverseShockVelocityEvolution(self)

    def GetContactDiscontinuityRadiusEvolution(self):
        return _gappa_swig.Astro_GetContactDiscontinuityRadiusEvolution(self)

    def GetContactDiscontinuityVelocityEvolution(self):
        return _gappa_swig.Astro_GetContactDiscontinuityVelocityEvolution(self)

    def CalculateForwardShockInRGWind(self, pars, tmin=1.e-2, tmax=1.e4, steps=200):
        return _gappa_swig.Astro_CalculateForwardShockInRGWind(self, pars, tmin, tmax, steps)

    def ForwardShockInRGWind(self, t, pars, profile):
        return _gappa_swig.Astro_ForwardShockInRGWind(self, t, pars, profile)

    def SetInterpolationMethod(self, intermeth):
        return _gappa_swig.Astro_SetInterpolationMethod(self, intermeth)

    def ToggleQuietMode(self):
        return _gappa_swig.Astro_ToggleQuietMode(self)

    def GetQuietMode(self):
        return _gappa_swig.Astro_GetQuietMode(self)

    def CalculateBField(self, xyz, component=-1):
        return _gappa_swig.Astro_CalculateBField(self, xyz, component)

    def CalculateBFieldPositions(self, pos, component=-1):
        return _gappa_swig.Astro_CalculateBFieldPositions(self, pos, component)

    def CalculateBFieldComponents(self, xyz, component=-1):
        return _gappa_swig.Astro_CalculateBFieldComponents(self, xyz, component)

    def CalculateBFieldStrengthComposition(self, xyz):
        return _gappa_swig.Astro_CalculateBFieldStrengthComposition(self, xyz)

    def CalculateBFieldStrength(self, xyz):
        return _gappa_swig.Astro_CalculateBFieldStrength(self, xyz)

    def LineOfSight(self, *args):
        return _gappa_swig.Astro_LineOfSight(self, *args)

# Register Astro in _gappa_swig:
_gappa_swig.Astro_swigregister(Astro)
class interp2d_spline(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    interp_object = property(_gappa_swig.interp2d_spline_interp_object_get, _gappa_swig.interp2d_spline_interp_object_set)
    xarr = property(_gappa_swig.interp2d_spline_xarr_get, _gappa_swig.interp2d_spline_xarr_set)
    yarr = property(_gappa_swig.interp2d_spline_yarr_get, _gappa_swig.interp2d_spline_yarr_set)
    zarr = property(_gappa_swig.interp2d_spline_zarr_get, _gappa_swig.interp2d_spline_zarr_set)

    def __init__(self):
        _gappa_swig.interp2d_spline_swiginit(self, _gappa_swig.new_interp2d_spline())
    __swig_destroy__ = _gappa_swig.delete_interp2d_spline

# Register interp2d_spline in _gappa_swig:
_gappa_swig.interp2d_spline_swigregister(interp2d_spline)

def interp2d_spline_alloc(T, xsize, ysize):
    return _gappa_swig.interp2d_spline_alloc(T, xsize, ysize)

def interp2d_spline_init(interp, xa, ya, za, xsize, ysize):
    return _gappa_swig.interp2d_spline_init(interp, xa, ya, za, xsize, ysize)

def interp2d_spline_free(interp):
    return _gappa_swig.interp2d_spline_free(interp)

def interp2d_spline_eval(interp, x, y, xa, ya):
    return _gappa_swig.interp2d_spline_eval(interp, x, y, xa, ya)

def interp2d_spline_eval_e(interp, x, y, xa, ya, z):
    return _gappa_swig.interp2d_spline_eval_e(interp, x, y, xa, ya, z)

def interp2d_spline_eval_deriv_x(interp, x, y, xa, ya):
    return _gappa_swig.interp2d_spline_eval_deriv_x(interp, x, y, xa, ya)

def interp2d_spline_eval_deriv_x_e(interp, x, y, xa, ya, z):
    return _gappa_swig.interp2d_spline_eval_deriv_x_e(interp, x, y, xa, ya, z)

def interp2d_spline_eval_deriv_y(interp, x, y, xa, ya):
    return _gappa_swig.interp2d_spline_eval_deriv_y(interp, x, y, xa, ya)

def interp2d_spline_eval_deriv_y_e(interp, x, y, xa, ya, z):
    return _gappa_swig.interp2d_spline_eval_deriv_y_e(interp, x, y, xa, ya, z)

def interp2d_spline_eval_deriv_xx(interp, x, y, xa, ya):
    return _gappa_swig.interp2d_spline_eval_deriv_xx(interp, x, y, xa, ya)

def interp2d_spline_eval_deriv_xx_e(interp, x, y, xa, ya, z):
    return _gappa_swig.interp2d_spline_eval_deriv_xx_e(interp, x, y, xa, ya, z)

def interp2d_spline_eval_deriv_yy(interp, x, y, xa, ya):
    return _gappa_swig.interp2d_spline_eval_deriv_yy(interp, x, y, xa, ya)

def interp2d_spline_eval_deriv_yy_e(interp, x, y, xa, ya, z):
    return _gappa_swig.interp2d_spline_eval_deriv_yy_e(interp, x, y, xa, ya, z)

def interp2d_spline_eval_deriv_xy(interp, x, y, xa, ya):
    return _gappa_swig.interp2d_spline_eval_deriv_xy(interp, x, y, xa, ya)

def interp2d_spline_eval_deriv_xy_e(interp, x, y, xa, ya, z):
    return _gappa_swig.interp2d_spline_eval_deriv_xy_e(interp, x, y, xa, ya, z)

def interp2d_spline_min_size(interp):
    return _gappa_swig.interp2d_spline_min_size(interp)

def interp2d_spline_name(interp):
    return _gappa_swig.interp2d_spline_name(interp)
class interp2d_type(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_gappa_swig.interp2d_type_name_get, _gappa_swig.interp2d_type_name_set)
    min_size = property(_gappa_swig.interp2d_type_min_size_get, _gappa_swig.interp2d_type_min_size_set)
    alloc = property(_gappa_swig.interp2d_type_alloc_get, _gappa_swig.interp2d_type_alloc_set)
    init = property(_gappa_swig.interp2d_type_init_get, _gappa_swig.interp2d_type_init_set)
    eval = property(_gappa_swig.interp2d_type_eval_get, _gappa_swig.interp2d_type_eval_set)
    eval_deriv_x = property(_gappa_swig.interp2d_type_eval_deriv_x_get, _gappa_swig.interp2d_type_eval_deriv_x_set)
    eval_deriv_y = property(_gappa_swig.interp2d_type_eval_deriv_y_get, _gappa_swig.interp2d_type_eval_deriv_y_set)
    eval_deriv_xx = property(_gappa_swig.interp2d_type_eval_deriv_xx_get, _gappa_swig.interp2d_type_eval_deriv_xx_set)
    eval_deriv_xy = property(_gappa_swig.interp2d_type_eval_deriv_xy_get, _gappa_swig.interp2d_type_eval_deriv_xy_set)
    eval_deriv_yy = property(_gappa_swig.interp2d_type_eval_deriv_yy_get, _gappa_swig.interp2d_type_eval_deriv_yy_set)
    free = property(_gappa_swig.interp2d_type_free_get, _gappa_swig.interp2d_type_free_set)

    def __init__(self):
        _gappa_swig.interp2d_type_swiginit(self, _gappa_swig.new_interp2d_type())
    __swig_destroy__ = _gappa_swig.delete_interp2d_type

# Register interp2d_type in _gappa_swig:
_gappa_swig.interp2d_type_swigregister(interp2d_type)
class interp2d(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    type = property(_gappa_swig.interp2d_type_get, _gappa_swig.interp2d_type_set)
    xmin = property(_gappa_swig.interp2d_xmin_get, _gappa_swig.interp2d_xmin_set)
    xmax = property(_gappa_swig.interp2d_xmax_get, _gappa_swig.interp2d_xmax_set)
    ymin = property(_gappa_swig.interp2d_ymin_get, _gappa_swig.interp2d_ymin_set)
    ymax = property(_gappa_swig.interp2d_ymax_get, _gappa_swig.interp2d_ymax_set)
    xsize = property(_gappa_swig.interp2d_xsize_get, _gappa_swig.interp2d_xsize_set)
    ysize = property(_gappa_swig.interp2d_ysize_get, _gappa_swig.interp2d_ysize_set)
    state = property(_gappa_swig.interp2d_state_get, _gappa_swig.interp2d_state_set)

    def __init__(self):
        _gappa_swig.interp2d_swiginit(self, _gappa_swig.new_interp2d())
    __swig_destroy__ = _gappa_swig.delete_interp2d

# Register interp2d in _gappa_swig:
_gappa_swig.interp2d_swigregister(interp2d)

def interp2d_type_min_size(T):
    return _gappa_swig.interp2d_type_min_size(T)

def interp2d_min_size(interp):
    return _gappa_swig.interp2d_min_size(interp)

def interp2d_name(interp):
    return _gappa_swig.interp2d_name(interp)

def interp2d_alloc(T, xsize, ysize):
    return _gappa_swig.interp2d_alloc(T, xsize, ysize)

def interp2d_init(interp, xa, ya, za, xsize, ysize):
    return _gappa_swig.interp2d_init(interp, xa, ya, za, xsize, ysize)

def interp2d_free(interp):
    return _gappa_swig.interp2d_free(interp)

def interp2d_eval(interp, xarr, yarr, zarr, x, y, xa, ya):
    return _gappa_swig.interp2d_eval(interp, xarr, yarr, zarr, x, y, xa, ya)

def interp2d_eval_no_boundary_check(interp, xarr, yarr, zarr, x, y, xa, ya):
    return _gappa_swig.interp2d_eval_no_boundary_check(interp, xarr, yarr, zarr, x, y, xa, ya)

def interp2d_eval_e(interp, xarr, yarr, zarr, x, y, xa, ya, z):
    return _gappa_swig.interp2d_eval_e(interp, xarr, yarr, zarr, x, y, xa, ya, z)

def interp2d_eval_e_no_boundary_check(interp, xarr, yarr, zarr, x, y, xa, ya, z):
    return _gappa_swig.interp2d_eval_e_no_boundary_check(interp, xarr, yarr, zarr, x, y, xa, ya, z)

def interp2d_eval_deriv_x(interp, xarr, yarr, zarr, x, y, xa, ya):
    return _gappa_swig.interp2d_eval_deriv_x(interp, xarr, yarr, zarr, x, y, xa, ya)

def interp2d_eval_deriv_x_e(interp, xarr, yarr, zarr, x, y, xa, ya, z):
    return _gappa_swig.interp2d_eval_deriv_x_e(interp, xarr, yarr, zarr, x, y, xa, ya, z)

def interp2d_eval_deriv_y(interp, xarr, yarr, zarr, x, y, xa, ya):
    return _gappa_swig.interp2d_eval_deriv_y(interp, xarr, yarr, zarr, x, y, xa, ya)

def interp2d_eval_deriv_y_e(interp, xarr, yarr, zarr, x, y, xa, ya, z):
    return _gappa_swig.interp2d_eval_deriv_y_e(interp, xarr, yarr, zarr, x, y, xa, ya, z)

def interp2d_eval_deriv_xx(interp, xarr, yarr, zarr, x, y, xa, ya):
    return _gappa_swig.interp2d_eval_deriv_xx(interp, xarr, yarr, zarr, x, y, xa, ya)

def interp2d_eval_deriv_xx_e(interp, xarr, yarr, zarr, x, y, xa, ya, z):
    return _gappa_swig.interp2d_eval_deriv_xx_e(interp, xarr, yarr, zarr, x, y, xa, ya, z)

def interp2d_eval_deriv_yy(interp, xarr, yarr, zarr, x, y, xa, ya):
    return _gappa_swig.interp2d_eval_deriv_yy(interp, xarr, yarr, zarr, x, y, xa, ya)

def interp2d_eval_deriv_yy_e(interp, xarr, yarr, zarr, x, y, xa, ya, z):
    return _gappa_swig.interp2d_eval_deriv_yy_e(interp, xarr, yarr, zarr, x, y, xa, ya, z)

def interp2d_eval_deriv_xy(interp, xarr, yarr, zarr, x, y, xa, ya):
    return _gappa_swig.interp2d_eval_deriv_xy(interp, xarr, yarr, zarr, x, y, xa, ya)

def interp2d_eval_deriv_xy_e(interp, xarr, yarr, zarr, x, y, xa, ya, z):
    return _gappa_swig.interp2d_eval_deriv_xy_e(interp, xarr, yarr, zarr, x, y, xa, ya, z)

