name: CI

on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request:

jobs:
  python:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-12
          - os: macos-14

    steps:
      
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu)
        if : ${{ contains(matrix.os,  'ubuntu') }}
        run: |
          sudo apt update
          sudo apt install -y libgsl-dev swig

      - name: install dependencies (macos)
        if : ${{ contains(matrix.os, 'macos') }}
        run: |
          brew install swig gsl

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install python-deps
        run: |
          python -m pip install numpy matplotlib pytest

      - name: build
        run: |
          pip install -vv .

      - name: test
        run: |
          pytest unit_tests --color=yes -v
